services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8581"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 86400
    depends_on:
      homebridge:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "watchtower", "--version"]
      interval: 1m
      timeout: 10s
      retries: 3
